In [ ]:
from fastai.vision.all import *

In [ ]:
path = untar_data(URLs.MNIST_SAMPLE)

In [ ]:
path.ls()

In [ ]:
(path/'train').ls()

In [ ]:
uchlar = (path/'train'/'3').ls().sorted()
yettilar = (path/'train'/'7').ls().sorted()
uchlar

In [ ]:
rasm3_path = uchlar[125]
rasm3 = Image.open(rasm3_path)
rasm3

In [ ]:
array(rasm3)[4:10, 4:10]

In [ ]:
tensor(rasm3)[4:10, 4:10]

In [ ]:
rasm3_t = tensor(rasm3)
df = pd.DataFrame(rasm3_t)
df.style.set_properties(**{'font-size':'6pt'}).background_gradient('Reds')

In [ ]:
uch_tensors = [tensor(Image.open(o)) for o in uchlar]
yetti_tensors = [tensor(Image.open(o)) for o in yettilar]
len(uch_tensors), len(yetti_tensors)

In [ ]:
show_image(uch_tensors[1])

In [ ]:
stacked_yettilar = torch.stack(yetti_tensors).float()/255
stacked_uchlar = torch.stack(uch_tensors).float()/255
stacked_uchlar.shape

In [ ]:
len(stacked_uchlar.shape)

In [ ]:
stacked_uchlar.ndim

In [ ]:
mean3 = stacked_uchlar.mean(0)
show_image(mean3)

In [ ]:
mean7 = stacked_yettilar.mean(0)
show_image(mean7)

In [ ]:
a_3 = stacked_uchlar[1]
show_image(a_3)

In [ ]:
dist_3_abs = (a_3 - mean3).abs().mean()
dist_3_sqr = ((a_3 - mean3)**2).mean().sqrt()
dist_3_abs, dist_3_sqr

In [ ]:
dist_7_abs = (a_3 - mean7).abs().mean()
dist_7_sqr = ((a_3 - mean7)**2).mean().sqrt()
dist_7_abs, dist_7_sqr

In [ ]:
F.l1_loss(a_3.float(), mean7), F.mse_loss(a_3, mean7).sqrt()

In [ ]:
data = [[1, 2, 3],[4, 5, 6]]
arr = array(data)
tns = tensor(data)

In [ ]:
arr    #numpy

natija: ↓↓↓↓
array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
tns    #pytorch

natija: ↓↓↓↓
array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
tns[1]

natija: ↓↓↓↓
tensor([4, 5, 6])

In [ ]:
tns[:,1]

natija: ↓↓↓↓
tensor([2, 5])

In [ ]:
tns[1, 1:3]

natija: ↓↓↓↓
tensor([5, 6])

In [ ]:
tns + 1

natija: ↓↓↓↓
tensor([[2, 3, 4],
        [5, 6, 7]])

In [ ]:
tns.type()

In [ ]:
tns * 1.5

natija: ↓↓↓↓
tensor([[1.5000, 3.0000, 4.5000],
        [6.0000, 7.5000, 9.0000]])

In [ ]:
valid_3_tens = torch.stack([tensor(Image.open(o))
                           for o in (path/'valid'/'3').ls()])
valid_3_tens = valid_3_tens.float()/255

valid_7_tens = torch.stack([tensor(Image.open(o))
                            for o in (path/'valid'/'7').ls()])
valid_7_tens = valid_7_tens.float()/255

valid_3_tens.shape, valid_7_tens.shape

In [ ]:
def mnist_distance(a, b): return (a-b).abs().mean((-1, -2))

#misol
mnist_distance(a_3, mean3)

In [ ]:
valid_3_dist = mnist_distance(valid_3_tens, mean3)
valid_3_dist, valid_3_dist.shape

In [ ]:
tensor([1, 2, 3]) + tensor([1, 1, 1])

In [ ]:
(valid_3_tens - mean3).shape

In [ ]:
# funksiya yaratib olamiz:
def is_3(x): return mnist_distance(x, mean3) < mnist_distance(x, mean7)

In [ ]:
is_3(a_3), is_3(a_3).float()

In [ ]:
is_3(valid_3_tens)

In [ ]:
accuracy_3s = is_3(valid_3_tens).float().mean()
accuracy_7s = (1-is_3(valid_7_tens).float()).mean()

accuracy_3s, accuracy_7s, (accuracy_3s + accuracy_7s)/2

In [ ]:
def f(x): return x**2

In [ ]:
def plot_function(f, title=None, min=-2.1, max=2.1, color='b', ylim=None):
    x = torch.linspace(min,max, 100)[:,None]
    if ylim:
      plt.ylim(ylim)
    plt.plot(x, f(x), color)
    if title is not None:
      plt.title(title)


In [ ]:
plot_function(f, 'x^2')
plt.xlabel('x')
plt.ylabel('x**2')
plt.show()

In [ ]:
plot_function(f, 'x^2')
plt.xlabel('x')
plt.ylabel('x**2')
plt.scatter(-1.5, f(-1.5), color='red')

In [ ]:
xt = tensor(3.).requires_grad_()

In [ ]:
yt = f(xt)
yt

In [ ]:
yt.backward()

In [ ]:
xt.grad

In [ ]:
xt = tensor([3., 4., 10.]).requires_grad_()
xt

In [ ]:
def f(x): return (x**2).sum()

yt = f(xt)
yt

In [ ]:
yt.backward()
xt.grad

In [ ]:
time = torch.arange(0, 20).float()
time

In [ ]:
speed = torch.randn(20)*3  + 0.75*(time - 9.5)**2 + 1
plt.scatter(time, speed)

In [ ]:
def f(t, params):
  a, b, c = params
  return a(t**2) + (b*t) + c

In [ ]:
def mse(preds, targets): return ((preds-targets)**2).mean()

In [ ]:
params = torch.randn(3).requires_grad_()

In [ ]:
preds = f(time, params)

In [ ]:
def show_preds(preds, ax=None):
  if ax is None: ax=plt.subplots()[1]
  ax.scatter(time, speed)
  ax.scatter(time, to_np(preds), color='red')
  ax.set_ylim(-300, 100)

show_preds(preds)

In [ ]:
loss = mse(preds, speed)
loss

In [ ]:
loss.backward()
params.grad

In [ ]:
params.grad * 1e-5

In [ ]:
params

In [ ]:
lr = 1e-5
params.data -= lr * params.grad.data
params.grad = None

In [ ]:
preds = f(time, params)
mse(preds, speed)

In [ ]:
show_preds(preds)

In [ ]:
def apply_step(params, prn=True):
  preds = f(time, params)
  loss = mse(preds, speed)
  loss.backward()
  params.data -= lr * params.grad.data
  params.grad = None
  if prn: print(loss.item())
  return preds

In [ ]:
for i in range(10): apply_step(params)

In [ ]:
_, axs = plt.subplots(1, 4, figsize=(12, 3))
for ax in axs: show_preds(apply_step(params, False), ax)
plt.tight_layout()

In [ ]:
train_x = torch.cat([stacked_uchlar, stacked_yettilar]).view(-1, 28*28)

In [ ]:
train_y = tensor([1]*len(uchlar) + [0]*len(yettilar)).unsqueeze(1)
train_x.shape, train_y.shape

In [ ]:
dset = list(zip(train_x, train_y))
x, y = dset[0]
x.shape, y

In [ ]:
valid_x = torch.cat([valid_3_tens, valid_7_tens]).view(-1, 28*28)
valid_y = tensor([1]*len(valid_3_tens) + [0]*len(valid_7_tens)).unsqueeze(1)
valid_dset = list(zip(valid_x, valid_y))

In [ ]:
def init_params(size, std=1.0): return (torch.randn(size)*std).requires_grad_()

weights = init_params((28*28, 1))

In [ ]:
bias = init_params(1)

In [ ]:
(train_x[0] * weights.T).sum() + bias

In [ ]:
def linear1(xb): return xb@weights + bias
preds = linear1(train_x)
preds

In [ ]:
corrects = (preds>0.0).float() == train_y
corrects

In [ ]:
corrects.float().mean().item()

In [ ]:
weights[0] *= 1.0001

preds = linear1(train_x)
((preds>0.0).float() == train_y).float().mean().item()


In [ ]:
trgts = tensor([1, 0, 1])
prds = tensor([0.9, 0.4, 0.2])

In [ ]:
def mnist_loss(predictions, targets):
  return torch.where(targets==1, 1-predictions, predictions).mean()

In [ ]:
torch.where(trgts==1, 1-prds, prds)

In [ ]:
mnist_loss(prds, trgts)

In [ ]:
mnist_loss(tensor([0.9, 0.4, 0.8]), trgts)

In [ ]:
def sigmoid(x): return 1/(1+torch.exp(-x))

In [ ]:
plot_function(torch.sigmoid, title='Sigmoid', min=-4, max=4)

In [ ]:
def mnist_loss(predictions, targets):
  predictions = predictions.sigmoid()
  return torch.where(targets==1, 1-predictions, predictions).mean()

In [ ]:
coll = range(15)
dl = DataLoader(coll, batch_size=5, shuffle=True)
list(dl)

In [ ]:
ds = L(enumerate(string.ascii_lowercase))
ds

In [ ]:
dl = DataLoader(ds,batch_size=6, shuffle=True)
list(dl)

#Putting all together

In [ ]:
for x, y in dl:
  pred = model(x)
  loss = loss_func(pred, y)
  loss.backward()
  parameters -= parameters.grad * lr

In [ ]:
weights = init_params((28*28, 1))
bias = init_params(1)

In [ ]:
dl = DataLoader(dset, batch_size=256)
xb, yb = first(dl)
xb.shape, yb.shape

In [ ]:
valid_dl = DataLoader(valid_dset, batch_size=256)

In [ ]:
batch = train_x[:4]
batch.shape

In [ ]:
preds = linear1(batch)
preds

In [ ]:
tensor([[ 2.4172],
        [-0.6474],
        [-1.5187],
        [ 5.4886]], grad_fn=<AddBackward0>)

In [ ]:
loss = mnist_loss(preds, train_y[:4])
loss

In [ ]:
loss.backward()
weights.grad.shape, weights.grad.mean(), bias.grad

In [ ]:
def calc_grad(xb, yb, model):
  preds = model(xb)
  loss = mnist_loss(preds, yb)
  loss.backward()

In [ ]:
calc_grad(batch, train_y[:4], linear1)
weights.grad.mean(), bias.grad

In [ ]:
weights.grad.zero_()
bias.grad.zero_()

In [ ]:
def train_epoch(model, lr, params):
  for xb, yb in dl:
    calc_grad(xb, yb, model)
    for p in params:
      p.data -= p.grad*lr
      p.grad.zero_()

In [ ]:
(preds>0.0).float() == train_y[:4]

In [ ]:
def batch_accuracy(xb, yb):
  preds = xb.sigmoid()
  correct = (preds>0.5) == yb
  return correct.float().mean()

In [ ]:
batch_accuracy(linear1(batch), train_y[:4])

In [ ]:
def validate_epoch(model):
  accs = [batch_accuracy(model(xb), yb) for xb, yb in valid_dl]
  return round(torch.stack(accs).mean().item(), 4)

validate_epoch(linear1)

In [ ]:
lr = 1
params = weights, bias
train_epoch(linear1, lr, params)
validate_epoch(linear1)

In [ ]:
for i in range(20):
  train_epoch(linear1, lr,params)
  print(validate_epoch(linear1), end=' ')

In [ ]:
linear_model = nn.Linear(28*28, 1)

In [ ]:
w, b = linear_model.parameters()
w.shape, b.shape

In [ ]:
class BasicOptim:
  def __init__(self, params, lr): self.params,self.lr = list(params), lr

  def step(self, *args, **kwargs):
    for p in self.params: p.data -= p.grad.data * self.lr

  def zero_grad(self, *args, **kwargs):
    for p in self.params: p.grad = None

In [ ]:
opt = BasicOptim(linear_model.parameters(), lr)

In [ ]:
def train_epoch(model):
  for xb, yb in dl:
    calc_grad(xb, yb, model)
    opt.step()
    opt.zero_grad()

In [ ]:
validate_epoch(linear_model)

In [ ]:
def train_model(model, epochs):
  for i in range(epochs):
    train_epoch(model)
    print(validate_epoch(model), end=' ')

In [ ]:
train_model(linear_model, 20)

In [ ]:
linear_model = nn.Linear(28*28, 1)
opt = SGD(linear_model.parameters(), lr)
train_model(linear_model, 20)

In [ ]:
dls = DataLoaders(dl, valid_dl)

In [ ]:
learn = Learner(dls, nn.Linear(28*28, 1), opt_func=SGD,
                loss_func=mnist_loss, metrics=batch_accuracy)

In [ ]:
learn.fit(10, lr=lr)

In [ ]:
w1 = init_params((28*28, 30))
b1 = init_params(30)
w2 = init_params((30, 1))
b2 = init_params(1)

In [ ]:
def simple_net(xb):
  res = xb@w1 + b1
  res = res.max(tensor(0.0))
  res = res@w2 + b2
  return res

In [ ]:
plot_function(F.relu)

In [ ]:
simple_net = nn.Sequential(
    nn.Linear(28*28, 30),
    nn.ReLU(),
    nn.Linear(30, 1)
)

In [ ]:
learn = Learner(dls, simple_net, opt_func=SGD,
                loss_func=mnist_loss, metrics=batch_accuracy)
learn.fit(40, 0.1)

In [ ]:
plt.plot(L(learn.recorder.values).itemgot(2))

In [ ]:
learn.recorder.values[-1][2]

In [ ]:
dls = ImageDataLoaders.from_folder(path)
learn = cnn_learner(dls, resnet18, pretrained=False,
                    loss_func=F.cross_entropy, metrics=accuracy)

learn.fit_one_cycle(1, 0.1)